config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"

  post 'search', to: 'search#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  post_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string
#  body        :string
#  views_count :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Post < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  index_name "my_custom_post_index"

  has_many :comments, dependent: :destroy

  settings analysis: {
    "filter": {
      "custom_synonym_filter": {
        "type": "synonym",
        "synonyms": [
          "may tinh => laptop",
        ]
      }
    },
    analyzer: {
      asciifolding_custom: {
        type:      'custom',
        tokenizer: 'standard',
        filter:    %w[lowercase asciifolding custom_synonym_filter]
      }
    }
  }

  mapping do
    indexes :id, type: :integer
    indexes :title, type: :text, analyzer: 'asciifolding_custom'
    indexes :body, type: :text, analyzer: 'snowball'
    indexes :comments do
      indexes :id, type: :integer
      indexes :body, type: :text
    end
  end

  def as_indexed_json(_options = {})
    as_json(
      methods: %i[custom_post_method],
      # include: [:comments],
      include: {
        comments: { only: [:id, :body] },
      }
    )
  end

  def custom_post_method
    self.title.split.first
  end

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: %w[title body]
          }
        }
      }
    )
  end

  # def self.search(query)
  #   __elasticsearch__.search(
  #     {
  #       query: {
  #         multi_match: {
  #           query: query,
  #           fields: %w[title body],
  #           "fuzziness": 1
  #         }
  #       }
  #     }
  #   )
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to comments_path, status: :see_other, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def create
    @result = search_for_posts

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update('suggestions', partial: 'search/suggestions', locals: {results: @result})
      end
    end
  end

  private

  def search_for_posts
    if params[:query].blank?
      Post.all
    else
      Post.search(params[:query]).records
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Body:</strong>
    <%= comment.body %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Post:</strong>
    <%= comment.post_id %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Views count:</strong>
    <%= post.views_count %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, class: "contents") do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul class="list-disc ml-6">
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 4, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": comment.errors[:body].none?, "border-red-400 focus:outline-red-600": comment.errors[:body].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :post_id %>
    <%= form.text_field :post_id, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": comment.errors[:post_id].none?, "border-red-400 focus:outline-red-600": comment.errors[:post_id].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<% content_for :title, "Editing comment" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing comment</h1>

  <%= render "form", comment: @comment %>

  <%= link_to "Show this comment", @comment, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to comments", comments_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/comments/index.html.erb
<% content_for :title, "Comments" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Comments</h1>
    <%= link_to "New comment", new_comment_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="comments" class="min-w-full">
    <% if @comments.any? %>
      <% @comments.each do |comment| %>
        <%= render comment %>
        <p>
          <%= link_to "Show this comment", comment, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
        </p>
      <% end %>
    <% else %>
      <p class="text-center my-10">No comments found.</p>
    <% end %>
  </div>
</div>

app/views/comments/new.html.erb
<% content_for :title, "New comment" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New comment</h1>

  <%= render "form", comment: @comment %>

  <%= link_to "Back to comments", comments_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/comments/show.html.erb
<% content_for :title, "Showing comment" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing comment</h1>

  <%= render @comment %>

  <%= link_to "Edit this comment", edit_comment_path(@comment), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to comments", comments_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this comment", @comment, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElasticsearchDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "p-2.5 bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-1/2" %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body, class: "p-2.5 bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-1/2" %>
  </div>

  <div>
    <%= form.label :views_count, style: "display: block" %>
    <%= form.number_field :views_count, class: "p-2.5 bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-1/2" %>
  </div>

  </br>
  <div>
    <%= form.submit class: "cursor-pointer bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"%>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

  <p>
    <strong>Views count:</strong>
    <%= post.views_count %>
  </p>

</div>

app/views/posts/_posts.html.erb
<div class="mt-5 p-4 border border-gray-300 rounded-lg">
  <h2>
    <strong>Title:</strong>
    <%= post.title %>
  </h2>

  <h2>
    <strong>Body:</strong>
    <%= post.body %>
  </h2>

  <h2>
    <strong>Views count:</strong>
    <%= post.views_count %>
  </h2>

  <p class="text-blue-800">
    <%= link_to "Show this post", post %>
  </p>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-4xl text-center mt-5 mb-4">Posts</h1>

<div class="flex justify-center">
  <%= render partial: 'search/form', locals: { results: [] } %>
</div>

<div class="flex justify-end mx-10">
  <%= link_to "New post", new_post_path, class: "cursor-pointer bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
</div>

<div id="posts" class="mt-4 mx-10">
  <%= render partial: 'posts/posts', collection: @posts, as: :post %>
</div>

app/views/posts/new.html.erb
<h1 class="font-bold text-4xl">New post</h1>
</br>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path, class: "cursor-pointer bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>
<br/>
<h1 class="font-bold">Comments:</h1>
<% if @post.comments.any? %>
  <ul class="list-disc ml-4">
    <% @post.comments.each do |comment| %>
      <li><%= comment.body %></li>
    <% end %>
  </ul>
<% end %>

<br/>
<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/search/_form.html.erb
<%= form_with(url: '/', method: :post, class: 'w-96', data: {
  controller: 'search', action: 'keyup->search#suggestions', suggestion_url: search_url
}) do |f| %>
  <div class="relative">
    <%= f.text_field :query, data: {search_target: 'input', action: 'blur->search#hideSuggestions'},
                     class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-5 p-2.5',
                     autocomplete: 'off', placeholder: 'Search...'
    %>

    <div class="absolute inset-y-0 right-0 flex item-center">
      <%= f.submit 'Search', class: "cursor-pointer bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    </div>

    <div id="suggestions" class="absolute w-full mt-2 bg-white rounded-lg shadow-lg" data-search-target='suggestions' >
      <%= render 'search/suggestions', results: results %>
    </div>
  </div>
<% end %>

app/views/search/_suggestions.html.erb
<% if results.any? %>
  <div class="absolute w-full overflow-y-auto max-h-80 bg-white rounded-lg shadow-lg">
    <% results.each do |post| %>
      <div class="p-2 border-b border-gray-300 hover:bg-gray-100">
        <%= link_to post.title, post, class: 'text-blue-500' %>
        <%= content_tag :p, post.body, class: 'text-gray-500' %>
      </div>
    <% end %>
  </div>
<% end %>